### ISSUE TITLE
Error when running copylog.php in line 9

### ISSUE THREAD

**Issue by breinntaguilar** [rroble/copylog#1]
When running copylog.php, I get this issue in line 9.

_breinn@lemonade:~/Documents/copylog-master$ php copylog.php 

Warning: require_once(/Users/breinn/Documents/copylog-master/vendor/autoload.php): failed to open stream: No such file or directory in /Users/breinn/Documents/copylog-master/copylog.php on line 9

Fatal error: require_once(): Failed opening required '/Users/breinn/Documents/copylog-master/vendor/autoload.php' (include_path='.:') in /Users/breinn/Documents/copylog-master/copylog.php on line 9_

How to fix this master gaps? Please help. 
We wanted to use your script to copy our logs from client JIRA to our internal JIRA just like with Alpha.
Your help is greatly appreciated.

Thanks!

**Comment by breinntaguilar** [comment]
I run 'composer install' in the folder of the copylog and I got another error

breinn@lemonade:~/Documents/copylog-master$ php copylog.php 

Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Logger.php on line 248

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/Users/breinn/Documents/copylog-master/logs/copylog.log" could not be opened: failed to open stream: No such file or directory' in /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84
Stack trace:
#0 /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Logger.php(473): Monolog\Logger->addRecord(200, 'START', Array)
#3 /Users/breinn/Documents/copylog-master/copylog.php(23): Monolog\Logger->info('START')
#4 {main}
  thrown in /Users/breinn/Documents/copylog-master/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84
